import type { OptionIcon } from "@legacy-building/backend/convex/onboarding/questions";
import {
	BookOpen,
	Camera,
	CircleQuestionMark,
	Clock,
	Compass,
	Eye,
	Footprints,
	Gift,
	GitBranch,
	Globe,
	GraduationCap,
	Heart,
	HeartPulse,
	Hourglass,
	House,
	Images,
	Infinity as InfinityIcon,
	Layers,
	Leaf,
	Lightbulb,
	type LucideIcon,
	MessageSquare,
	MessagesSquare,
	Mic,
	PenLine,
	Ribbon,
	Smile,
	Sparkles,
	TrendingUp,
	Trophy,
	User,
	UserPlus,
	Users,
	UsersRound,
	Video,
} from "lucide-react-native";

/**
 * Shared icon keys mapped to the Lucide glyphs used in the Figma designs — the
 * same set `apps/web` uses, so both clients draw identical icons. Typed as a
 * full Record, so adding a key to `OPTION_ICONS` fails the build here until it
 * has an icon.
 */
export const ONBOARDING_ICONS: Record<OptionIcon, LucideIcon> = {
	album: Images,
	book: BookOpen,
	camera: Camera,
	chat: MessageSquare,
	chats: MessagesSquare,
	clock: Clock,
	compass: Compass,
	everything: InfinityIcon,
	eye: Eye,
	family: UsersRound,
	footsteps: Footprints,
	gift: Gift,
	globe: Globe,
	growth: TrendingUp,
	heart: Heart,
	heartPulse: HeartPulse,
	home: House,
	hourglass: Hourglass,
	idea: Lightbulb,
	leaf: Leaf,
	lineage: GitBranch,
	mic: Mic,
	mix: Layers,
	people: Users,
	person: User,
	personAdd: UserPlus,
	question: CircleQuestionMark,
	ribbon: Ribbon,
	school: GraduationCap,
	smile: Smile,
	sparkle: Sparkles,
	trophy: Trophy,
	video: Video,
	write: PenLine,
};
